runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

handlers: 
- url: /styles
  static_dir: styles

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /.*
  script: main.app
